#!/bin/sh

# bspwm options
bspc config border_width 0
bspc config normal_border_color "#5677fc"
bspc config active_border_color "#5677fc"
bspc config focused_border_color "#5677fc"
bspc config window_gap 20
bspc config top_padding 75
bspc config right_padding 50
bspc config bottom_padding 50
bspc config left_padding 50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# set up tags
bspc monitor DVI-I-2 -d I II III IV V
bspc monitor DVI-I-3 -d VI VII VIII IX X

# rules
bspc rule -a urxvt floating=on
bspc rule -a Steam floating=on
bspc rule -a ArmoryQt.py floating=on
bspc rule -a Wine floating=on
bspc rule -a processing-app-Base floating=on

# start the panel
panel &
