#! /bin/sh
bspc config border_width	3
bspc config window_gap		25

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true

bspc monitor DVI-I-2 -d $(echo -e '\uf120') $(echo -e '\uf268') $(echo -e '\uf023') $(echo -e '\uf15a') $(echo -e '\uf1e8')
bspc monitor DVI-I-3 -d $(echo -e '\uf268') $(echo -e '\uf11b') $(echo -e '\uf003') $(echo -e '\uf110') $(echo -e '\uf110') 

bspc config normal_border_color '#282828'
bspc config focused_border_color '#d5c4a1'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

# rules
bspc rule -a urxvt floating=on
bspc rule -a Steam floating=on
bspc rule -a ArmoryQt.py floating=on
bspc rule -a Wine floating=on
bspc rule -a processing-app-Base floating=on

# start the panel
panel &
