#! /bin/sh
bspc config border_width	3
bspc config window_gap		25

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true

bspc monitor eDP-1 -d I II III IV V VI VII

bspc config normal_border_color '#464B50'
bspc config focused_border_color '#464B50'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

# rules
bspc rule -a URxvt state=floating
bspc rule -a Steam desktop=^7
bspc rule -a Thunderbird desktop=^4
bspc rule -a KeePass2 desktop=^3
bspc rule -a hon-x86_64 desktop=^7 state=fullscreen

# Panel starts from .xinitrc
